/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemDescriptorSummary } from './item-descriptor-summary';
import { FactorySiteInput } from './factory-site-input';
import { FactoryPlanningRequest } from './factory-planning-request';
import { RecipeSummary } from './recipe-summary';


export interface CraftingMachineSiteInput extends FactorySiteInput { 
    recipe: RecipeSummary;
}
export namespace CraftingMachineSiteInput {
}


