/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecipeDto } from './recipe-dto';
import { FactorySiteInput } from './factory-site-input';
import { FactoryPlanningRequest } from './factory-planning-request';
import { ItemDescriptorDto } from './item-descriptor-dto';


export interface CraftingMachineSiteInput extends FactorySiteInput { 
    recipe: RecipeDto;
}
export namespace CraftingMachineSiteInput {
}


