/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecipeDto } from './recipe-dto';
import { FactoryNode } from './factory-node';
import { ItemDescriptorDto } from './item-descriptor-dto';
import { CraftingMachineDto } from './crafting-machine-dto';


export interface CraftingSiteNode extends FactoryNode { 
    automaton: CraftingMachineDto;
    recipe: RecipeDto;
}
export namespace CraftingSiteNode {
}


