/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FactorySiteInput } from './factory-site-input';
import { FactoryPlanningRequest } from './factory-planning-request';
import { Extractor } from './extractor';
import { ItemDescriptorDto } from './item-descriptor-dto';


export interface ExtractingSiteInput extends FactorySiteInput { 
    extractor: Extractor;
}
export namespace ExtractingSiteInput {
}


