/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FactorySiteRequest } from './factory-site-request';


export interface ExtractingSiteRequest extends FactorySiteRequest { 
    extractorClass: string;
}
export namespace ExtractingSiteRequest {
}


