/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Destination } from './destination';
import { ItemDescriptorSummary } from './item-descriptor-summary';
import { Automaton } from './automaton';
import { FactorySiteIO } from './factory-site-io';


export interface FactorySite { 
    destinations: Array<Destination>;
    childs: Array<FactorySite>;
    requiredMachines: number;
    targetDescriptor: ItemDescriptorSummary;
    targetAmountPerCycle: number;
    produces: Array<FactorySiteIO>;
    automaton: Automaton;
}

