/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecipeDto } from './recipe-dto';
import { ExtractingSiteInput } from './extracting-site-input';
import { CraftingMachineSiteInput } from './crafting-machine-site-input';
import { Extractor } from './extractor';
import { ItemDescriptorDto } from './item-descriptor-dto';


/**
 * @type FactoryPlanningRequest
 * @export
 */
export type FactoryPlanningRequest = CraftingMachineSiteInput | ExtractingSiteInput;

