/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FactorySiteRequest { 
    type: FactorySiteRequest.TypeEnum;
    itemClass: string;
    targetAmountPerCycle: number;
}
export namespace FactorySiteRequest {
    export type TypeEnum = 'ExtractorSite' | 'CraftingSite' | 'ItemSite';
    export const TypeEnum = {
        ExtractorSite: 'ExtractorSite' as TypeEnum,
        CraftingSite: 'CraftingSite' as TypeEnum,
        ItemSite: 'ItemSite' as TypeEnum
    };
}


