/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemDescriptorDto } from './item-descriptor-dto';


export interface FactoryNode {
    type: FactoryNode.TypeEnum;
  id: string;
    factorySiteTarget: ItemDescriptorDto;
    label: string;
}
export namespace FactoryNode {
  export type TypeEnum = 'ExtractorSite' | 'CraftingSite' | 'ItemSite' | 'ExtractionNode';
    export const TypeEnum = {
        ExtractorSite: 'ExtractorSite' as TypeEnum,
        CraftingSite: 'CraftingSite' as TypeEnum,
      ItemSite: 'ItemSite' as TypeEnum,
      ExtractionNode: 'ExtractionNode' as TypeEnum
    };
}


