/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Automaton } from './automaton';
import { FactorySiteIO } from './factory-site-io';
import { ItemDescriptorDto } from './item-descriptor-dto';


export interface FactoryNode { 
    type: FactoryNode.TypeEnum;
    factorySiteTarget: ItemDescriptorDto;
    targetAmountPerCycle: number;
    requiredMachines: number;
    automaton: Automaton;
    produces: Array<FactorySiteIO>;
    id: string;
    label: string;
}
export namespace FactoryNode {
    export type TypeEnum = 'ExtractorSite' | 'RecipeSite';
    export const TypeEnum = {
        ExtractorSite: 'ExtractorSite' as TypeEnum,
        RecipeSite: 'RecipeSite' as TypeEnum
    };
}


