/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemSiteNode } from './item-site-node';
import { CraftingSiteNode } from './crafting-site-node';
import { ExtractingSiteNode } from './extracting-site-node';
import { ExtractorEntity } from './extractor-entity';
import { FactorySiteIO } from './factory-site-io';
import { ItemDescriptorDto } from './item-descriptor-dto';
import { RecipeProducingDto } from './recipe-producing-dto';


/**
 * @type GraphBuilderFactoryNodeFactoryEdgeNodesInner
 * @export
 */
export type GraphBuilderFactoryNodeFactoryEdgeNodesInner = CraftingSiteNode | ExtractingSiteNode | ItemSiteNode;

