/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Extractor } from './extractor';


export interface ItemDescriptorSummary { 
    category: ItemDescriptorSummary.CategoryEnum;
    sinkablePoints?: number;
    iconSmall?: string;
    form?: string;
    extractedIn: Set<Extractor>;
    className: string;
    displayName: string;
}
export namespace ItemDescriptorSummary {
    export type CategoryEnum = 'Raw' | 'Biomass' | 'Building' | 'Equipment' | 'Craftable' | 'Vehicle' | 'Consumable' | 'PowerShard';
    export const CategoryEnum = {
        Raw: 'Raw' as CategoryEnum,
        Biomass: 'Biomass' as CategoryEnum,
        Building: 'Building' as CategoryEnum,
        Equipment: 'Equipment' as CategoryEnum,
        Craftable: 'Craftable' as CategoryEnum,
        Vehicle: 'Vehicle' as CategoryEnum,
        Consumable: 'Consumable' as CategoryEnum,
        PowerShard: 'PowerShard' as CategoryEnum
    };
}


