/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskCreationDto } from './task-creation-dto';


export interface PowerGeneratingSiteTaskCreationDto extends TaskCreationDto { 
    selectedFuel: string;
    powerGenerator: string;
    powerProducedInMegaWatt: number;
}
export namespace PowerGeneratingSiteTaskCreationDto {
}


