/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PowerGeneratorFuelRequires } from './power-generator-fuel-requires';
import { ItemIoDto } from './item-io-dto';


export interface PowerGeneratorDto { 
    className: string;
    currentPotential: number;
    fuelLoadAmount: number;
    powerProduction: number;
    fuel: Set<PowerGeneratorFuelRequires>;
    supplementalResource?: ItemIoDto;
    byproducts?: ItemIoDto;
}

