/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CraftingMachineDto } from './crafting-machine-dto';
import { ItemIoDto } from './item-io-dto';


export interface RecipeRequiringDto { 
    className: string;
    manufacturingDuration: number;
    displayName: string;
    manufacturedIn: Array<CraftingMachineDto>;
    ingredients: Array<ItemIoDto>;
}

