/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemDescriptorDto } from './item-descriptor-dto';


export interface RecipeIoDto { 
    item: ItemDescriptorDto;
    outputPerCycle: number;
    actualOutputPerCycle: number;
}

