/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecipeIoDto } from './recipe-io-dto';
import { CraftingMachineEntity } from './crafting-machine-entity';


export interface RecipeProducingDto { 
    id: string;
    className: string;
    manufacturingDuration: number;
    displayName: string;
    manufacturedIn: Array<CraftingMachineEntity>;
    producing: Array<RecipeIoDto>;
    manufacturingDurationByMinute: number;
}

