/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecipeIO } from './recipe-io';
import { CraftingMachine } from './crafting-machine';


export interface RecipeRequiringSummary { 
    ingredients: Array<RecipeIO>;
    manufacturingDuration: number;
    manufacturedIn: Array<CraftingMachine>;
    id: string;
    className: string;
    displayName: string;
}

