/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecipeDto } from './recipe-dto';
import { ExtractingSiteTaskDto } from './extracting-site-task-dto';
import { TaskIoDto } from './task-io-dto';
import { CraftingSiteTaskDto } from './crafting-site-task-dto';
import { PowerGeneratingSiteTaskDto } from './power-generating-site-task-dto';
import { TaskDto } from './task-dto';
import { PowerGeneratorDto } from './power-generator-dto';
import { ExtractorDto } from './extractor-dto';


/**
 * @type SaveTask200Response
 * @export
 */
export type SaveTask200Response = CraftingSiteTaskDto | ExtractingSiteTaskDto | PowerGeneratingSiteTaskDto | TaskDto;

