/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CraftingSiteTaskCreationDto } from './crafting-site-task-creation-dto';
import { ExtractingNode } from './extracting-node';
import { ExtractingSiteTaskCreationDto } from './extracting-site-task-creation-dto';
import { PowerGeneratingSiteTaskCreationDto } from './power-generating-site-task-creation-dto';


/**
 * @type SaveTaskRequest
 * @export
 */
export type SaveTaskRequest = CraftingSiteTaskCreationDto | ExtractingSiteTaskCreationDto | PowerGeneratingSiteTaskCreationDto;

