/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskCreationDto { 
    type: TaskCreationDto.TypeEnum;
    status: TaskCreationDto.StatusEnum;
}
export namespace TaskCreationDto {
    export type TypeEnum = 'CraftingSite' | 'ExtractingSite' | 'PowerGeneratingSite';
    export const TypeEnum = {
        CraftingSite: 'CraftingSite' as TypeEnum,
        ExtractingSite: 'ExtractingSite' as TypeEnum,
        PowerGeneratingSite: 'PowerGeneratingSite' as TypeEnum
    };
    export type StatusEnum = 'ToDo' | 'InProgress' | 'Disconnected' | 'Done';
    export const StatusEnum = {
        ToDo: 'ToDo' as StatusEnum,
        InProgress: 'InProgress' as StatusEnum,
        Disconnected: 'Disconnected' as StatusEnum,
        Done: 'Done' as StatusEnum
    };
}


