/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskLinkDto } from './task-link-dto';
import { ItemDescriptorMetadataDto } from './item-descriptor-metadata-dto';


export interface TaskIoDto { 
    id: string;
    amountPerMinute: number;
    item: ItemDescriptorMetadataDto;
    source?: TaskLinkDto;
    destination?: TaskLinkDto;
}

