/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GraphFactoryNodeFactoryEdge } from '../model/models';
import { PlanFactorySiteRequestInner } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FactoryPlannerControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param planFactorySiteRequestInner 
     */
    planFactorySite(planFactorySiteRequestInner: Array<PlanFactorySiteRequestInner>, extraHttpRequestParams?: any): Observable<GraphFactoryNodeFactoryEdge>;

}
