/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CraftingMachineSiteInput } from '../model/models';
import { ExtractingSiteInput } from '../model/models';
import { FactoryPlanningRequest } from '../model/models';
import { FactorySite } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FactoryPlannerControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param craftingMachineSiteInputExtractingSiteInput 
     */
    factoryPlanning(craftingMachineSiteInputExtractingSiteInput: CraftingMachineSiteInput | ExtractingSiteInput, extraHttpRequestParams?: any): Observable<FactorySite>;

}
