/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ItemDescriptorSummary } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ItemDescriptorControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param itemClassName 
     */
    findByClassName(itemClassName: string, extraHttpRequestParams?: any): Observable<ItemDescriptorSummary>;

    /**
     * 
     * 
     * @param displayName 
     */
    searchByDisplayNameLike(displayName: string, extraHttpRequestParams?: any): Observable<Array<ItemDescriptorSummary>>;

}
