/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ItemDescriptorDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ItemDescriptorControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param itemClassName 
     */
    findByClassName2(itemClassName: string, extraHttpRequestParams?: any): Observable<ItemDescriptorDto>;

    /**
     * 
     * 
     * @param displayName 
     */
    searchByDisplayNameLike1(displayName: string, extraHttpRequestParams?: any): Observable<Array<ItemDescriptorDto>>;

}
