/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PowerGeneratorDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PowerGeneratorControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    findAll(extraHttpRequestParams?: any): Observable<Array<PowerGeneratorDto>>;

    /**
     * 
     * 
     * @param className 
     */
    findByClassName1(className: string, extraHttpRequestParams?: any): Observable<PowerGeneratorDto>;

    /**
     * 
     * 
     * @param displayName 
     */
    searchByDisplayNameLike(displayName: string, extraHttpRequestParams?: any): Observable<Array<PowerGeneratorDto>>;

}
