/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RecipeProducingSummary } from '../model/models';
import { RecipeRequiringSummary } from '../model/models';
import { RecipeSummary } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RecipeControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param itemClass 
     */
    findAllByProducedItem(itemClass: string, extraHttpRequestParams?: any): Observable<Array<RecipeSummary>>;

    /**
     * 
     * 
     * @param recipeClassName 
     */
    findByClassNameProducing(recipeClassName: string, extraHttpRequestParams?: any): Observable<RecipeProducingSummary>;

    /**
     * 
     * 
     * @param recipeClassName 
     */
    findByClassNameRequiring(recipeClassName: string, extraHttpRequestParams?: any): Observable<RecipeRequiringSummary>;

}
