/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CraftingSiteTaskCreationDto } from '../model/models';
import { ExtractingSiteTaskCreationDto } from '../model/models';
import { PowerGeneratingSiteTaskCreationDto } from '../model/models';
import { SaveTask200Response } from '../model/models';
import { SaveTaskRequest } from '../model/models';
import { TaskGroupDto } from '../model/models';
import { TaskIOCreationRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TaskControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param groupId 
     * @param taskIOCreationRequest 
     */
    bindTask(groupId: string, taskIOCreationRequest: Array<TaskIOCreationRequest>, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    getGroupById(id: string, extraHttpRequestParams?: any): Observable<TaskGroupDto>;

    /**
     * 
     * 
     * @param groupId 
     * @param taskId 
     */
    getTask(groupId: string, taskId: string, extraHttpRequestParams?: any): Observable<SaveTask200Response>;

    /**
     * 
     * 
     * @param taskGroupDto 
     */
    saveGroup(taskGroupDto: TaskGroupDto, extraHttpRequestParams?: any): Observable<TaskGroupDto>;

    /**
     * 
     * 
     * @param groupId 
     * @param craftingSiteTaskCreationDtoExtractingSiteTaskCreationDtoPowerGeneratingSiteTaskCreationDto 
     */
    saveTask(groupId: string, craftingSiteTaskCreationDtoExtractingSiteTaskCreationDtoPowerGeneratingSiteTaskCreationDto: CraftingSiteTaskCreationDto | ExtractingSiteTaskCreationDto | PowerGeneratingSiteTaskCreationDto, extraHttpRequestParams?: any): Observable<SaveTask200Response>;

    /**
     * 
     * 
     * @param name 
     */
    searchGroupByDisplayNameLike(name: string, extraHttpRequestParams?: any): Observable<Array<TaskGroupDto>>;

}
